services:
  web:
    depends_on:
      - redis
      - db
      - solr
      - minio
    build: .
    ports:
        - "5000:5000"
    environment:
        - CKAN_REDIS_URL=redis://redis:6379/0
        - CKAN_SITE_URL=http://localhost:5000/
        - CKAN_SOLR_URL=http://solr:8983/solr/ckan
        - CKAN_SQLALCHEMY_URL=postgres://ckan:password@db/ckan
        - CKAN___BEAKER__SESSION__SECRET=supersecret
        - CKAN___CKANEXT__S3FILESTORE__AWS_ACCESS_KEY_ID=minio-access-key
        - CKAN___CKANEXT__S3FILESTORE__AWS_BUCKET_NAME=openup-ckan
        - CKAN___CKANEXT__S3FILESTORE__AWS_SECRET_ACCESS_KEY=minio-secret-key
        - CKAN___CKANEXT__S3FILESTORE__HOST_NAME=http://minio:9000
        - CKAN___CKANEXT__S3FILESTORE__REGION_NAME=eu-west-1
        - CKAN___CKANEXT__S3FILESTORE__SIGNATURE_VERSION=s3v4
    volumes:
      - ./bin/wait-for-deps.sh:/app/bin/wait-for-deps.sh
      - ./bin/connect-to-postgres.py:/app/bin/connect-to-postgres.py
      - ./bin/connect-to-solr.py:/app/bin/connect-to-solr.py
      - ./ckan.ini:/app/ckan.ini
      - ./who.ini:/app/who.ini
      - ckan-filestore:/var/lib/ckan
    command: ["/app/bin/wait-for-deps.sh", "paster", "serve", "ckan.ini"]

  worker:
    depends_on:
      - redis
      - db
      - solr
      - minio
    build: .
    environment:
        - CKAN_REDIS_URL=redis://redis:6379/0
        - CKAN_SITE_URL=http://localhost:5000/
        - CKAN_SOLR_URL=http://solr:8983/solr/ckan
        - CKAN_SQLALCHEMY_URL=postgres://ckan:password@db/ckan
        - CKAN___BEAKER__SESSION__SECRET=supersecret
        - CKAN___CKANEXT__S3FILESTORE__AWS_ACCESS_KEY_ID=minio-access-key
        - CKAN___CKANEXT__S3FILESTORE__AWS_BUCKET_NAME=openup-ckan
        - CKAN___CKANEXT__S3FILESTORE__AWS_SECRET_ACCESS_KEY=minio-secret-key
        - CKAN___CKANEXT__S3FILESTORE__HOST_NAME=http://minio:9000
        - CKAN___CKANEXT__S3FILESTORE__REGION_NAME=eu-west-1
        - CKAN___CKANEXT__S3FILESTORE__SIGNATURE_VERSION=s3v4
    volumes:
      - ./bin/wait-for-deps.sh:/app/bin/wait-for-deps.sh
      - ./bin/connect-to-postgres.py:/app/bin/connect-to-postgres.py
      - ./bin/connect-to-solr.py:/app/bin/connect-to-solr.py
      - ./ckan.ini:/app/ckan.ini
      - ./who.ini:/app/who.ini
      - ckan-filestore:/var/lib/ckan/default/storage
    command: ["/app/bin/wait-for-deps.sh", "paster", "--plugin=ckan", "jobs", "worker", "--config", "ckan.ini"]

  redis:
    image: redis:latest

  db:
    image: postgres:12.17
    environment:
      - POSTGRES_USER=ckan
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ckan
    volumes:
      - db-data:/var/lib/postgresql/data

  solr:
    build: https://github.com/OpenUpSA/openup-ckan-solr-dokku.git
    image: openup-ckan-solr
    ports:
        - "8983:8983"
    volumes:
      - solr-data:/opt/solr/server/solr/budgetportal/data

  minio:
    image: "minio/minio:RELEASE.2019-10-12T01-39-57Z"
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
      - MINIO_DOMAIN=minio
    command: minio --compat server data

volumes:
  ckan-filestore:
  db-data:
  solr-data:
  minio-data:
